const Router = require('express');
const router = new Router();
const categoryRouter = require('./categoryRouter');
const brandRouter = require('./brandRouter');
const productRouter = require('./productRouter');
const userRouter = require('./userRouter');
const basketRouter = require('./basketRouter');
const favoritesRouter = require('../modules/favorites/favorites.router');
const articleRouter = require('./articleRouter');
const bannerRouter = require('./bannerRouter');
const orderRouter = require('./orderRouter');
const FAQRouter = require('./FAQRouter');
const notificationRouter = require('./notificationRouter');
const promocodeRouter = require('./promocodeRouter');
const aboutRouter = require('./aboutRouter');
const fileRouter = require('./fileRouter');
const filterGroupRouter = require('./filterGroupRouter');
const filterOptionRouter = require('./filterOptionRouter');
const parameterRouter = require('./parameterRouter');
const typeRouter = require('./typeRouter');
const searchRouter = require('../modules/search/search.router');

router.use('/user', userRouter);
router.use('/category', categoryRouter);
router.use('/brand', brandRouter);
router.use('/type', typeRouter);
router.use('/product', productRouter);
router.use('/basket', basketRouter);
router.use('/favorites', favoritesRouter);
router.use('/article', articleRouter);
router.use('/banner', bannerRouter);
router.use('/order', orderRouter);
router.use('/faq', FAQRouter);
router.use('/notification', notificationRouter);
router.use('/promocode', promocodeRouter);
router.use('/about', aboutRouter);
router.use('/upload', fileRouter);
router.use('/filter_group', filterGroupRouter);
router.use('/filter_option', filterOptionRouter);
router.use('/parameter', parameterRouter);
router.use('/search', searchRouter);

module.exports = router;